### ISSUE TITLE
Error in ReadPolygon()

### ISSUE THREAD

**Issue by cesarhein** [gasparesganga/php-shapefile#1]
I get the following error reading a shape file:

PHP Stack trace:
PHP   1. {main}() /var/www/html/servicios/app-busqueda-de-parcelas/actualizacion_capas/convertir_shps_a_csvs.php:0
PHP   2. ShapeFile->getRecord() /var/www/html/actualizacion_capas/convertir_shps_a_csvs.php:45
PHP   3. ShapeFile->ReadPolygon() /var/www/html/actualizacion_capas/php-shapefile-master/src/shapefile.php:115
PHP Notice:  Undefined offset: 71997 in /var/www/html/servicios/app-busqueda-de-parcelas/actualizacion_capas/php-shapefile-master/src/shapefile.php on line 225

This  error is repeated indefinitely.
I solved the problem by swapping the lines 211 (if ($this->IsClockwise($rawpart['points'])) {) and 212 ($i++;) of the file "shapefile.php". But I'm not sure that's the right solution. 

This the line 45 of convertir_shps_a_csvs.php file:
while ($record = $ShapeFile->getRecord(SHAPEFILE::GEOMETRY_WKT)) {

Here is the shp that throw the error:
https://drive.google.com/folderview?id=0B20LrQtIoHC5fmlCOVVOM0FsZWhIckJDVHp3UWVLWlplSnZaR09xYzMyM2wyU0tXbW15Z1E&usp=sharing

**Comment by gasparesganga** [comment]
That's not a bug in the PHP ShapeFile class, but it's related to an invalid Polygon contained in the shapefile you provided.
Look for the _1515PA000000039_ item and you'll see it's not a valid Polygon, it has only 2 vertexes thus it should be a Linestring.

Currently the Class can't handle invalid shapefiles and/or geometries, so please be sure to check your shapefiles before.

PS: Swapping those lines will mess up the logic when reading valid Polygons, resulting in wrong results.

**Comment by cesarhein** [comment]
Ok! I'll fix the shapefile.
Thank You!

**Comment by cesarhein** [comment]
Just a comment...

I added this line: 
    **if(!isset($parts[$i])) continue;**
between lines 220 and 221  of "shapefile.php" file.

With this change PHP ShapeFile Class can read invalid shapefile without problems. This was very useful to me because I prefer read an invalid polygon instead of losing all polygons of the shapefile.

Please let me know if I fall into a serious error.

Thanks a lot!

**Comment by gasparesganga** [comment]
You should decrement `$i` as well before `continue;` otherwise you will get some missing indexes in your `$parts` array. If that's not a problem for you (ie. the code which handles the output from the library) then if should be fine.

I still think it's better to deal with invalid files and geometries beforehand, or, better, implement a strategy in the library to handle and report them.

Thank you for using my library.
