### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by allartk** [gasparesganga/php-shapefile#12]
Hello,

Parsing the dbf values, i found you pad all null values with * in readString

I have two problems with it:
* Original null values are lost, eg when importing to some database.
* Invalid input *************** for datetime on line 421 results in invalid datetime object -0001-11-30

**Comment by gasparesganga** [comment]
Hi,
DBF files that come with ESRI Shapefiles can follow either dBASE III or dBASE IV specs, which do *NOT* allow `null` values. Maybe your DBF file follow newer or custom specifications that allow null values? It's a common *bad practice* to use dBASE Plus files, but the original ESRI specs are very clear about that.

The `*` you are referring to in my code is probably the repeater argument passed to PHP `unpack` function. This does not represent a *padding character*, rather it specifies the amount of data being read. Please refer to the PHP [documentation ](http://php.net/manual/en/function.pack.php).

Anyways, if you send me some test data (a shapefile with this DBF containing null values) I will investigate and eventually come up with a fix to support it, so other people will be able to use the same kind of DBF files.
Also, it would be great to know the source of your DBF, ie. a specific GIS software or something else.
We are used to take for granted what *big software packages* procude, but for example QGIS fails to fully comply to dBase specs, with a missing byte at the end of the DBF files that exports.

**Comment by allartk** [comment]
The source is geoserver: 
[testshapes.zip](https://github.com/gasparesganga/php-shapefile/files/1314597/testshapes.zip)
. Qgis display the values as NULL. 

I am indeed not familiar with the working of dbf.

**Comment by gasparesganga** [comment]
If you open those DBF files with a simple text editor, you will notice those ********************************* are already there. It is probably some convention used by modern softwares to interpret them as a `null` values.

As I wrote in my last comment, QGIS sometimes fail to comply to standards. I'll try to analyze those files on a binary level and see if I can support them somehow.
Unfortunately dBASE files are pretty old and flawed and there are so many *non-standard* files out there which mix specifications among different versions.
