### ISSUE TITLE
fread warning

### ISSUE THREAD

**Issue by flippedbits** [gasparesganga/php-shapefile#14]
Not sure if this is an issue with the shapefile or with the code but I am getting an error of "**Warning: fread(): Length parameter must be greater than 0**" when trying to read this shape file.

It looks to be coming from line 455 of ShapeFile.php and is caused because $field['size'] is 'null'.

This is the shape file I was testing: http://www.mapcruzin.com/liberia-shapefiles/roads.zip

**Comment by gasparesganga** [comment]
Thanks for the feedback, it was a pretty trivial bug.
Cheers

**Comment by DorinMol** [comment]
Hi @gasparesganga, i'm having the same issue. Is this going to be solved in feature versions ?. Thank you.

PS: nvm, just saw the changes.

**Comment by gasparesganga** [comment]
This bug was already fixed with in v2.4.3, thus eventually it cannot be for the same cause.

Please let me know if you are experiencing other issues, as I am currently working at a complete refactoring for v3.
