### ISSUE TITLE
Validated polygons with “ring not closed” 

### ISSUE THREAD

**Issue by ken-muturi** [gasparesganga/php-shapefile#24]
Is it possible to check/validated shape-files with polygons with rings not closed.  

See this https://gis.stackexchange.com/questions/170942/fixing-polygons-with-ring-not-closed-errors?rq=1

**Comment by gasparesganga** [comment]
The concept of *repairing an invalid geometry* is not very simple... for trivial issues, like a missing point (usually the last *closing point* of a polygon, which must be the same as its first one), it could be as simple as adding it, but never take that for granted: the example shown in that StackExchange discussion is simple, but imagine a slightly more complex one, with a convex polygon shape that would originate a deadly **self-intersection**  when trying to connect the last point with the first one...!

The scope for that are GIS software (and some pricey ones justify their price with tools and features like that...) and specialized libraries, not a Shapefile library.
If you are trying to **read** a shapefile you can set `OPTION_ENFORCE_POLYGON_CLOSED_RINGS` to `false` and try to repair those polygons using some external logic/library.
If you are **writing** a shapefile you can set [Polygons](https://gasparesganga.com/labs/php-shapefile/#polygon__construct) and [MultiPolygons](https://gasparesganga.com/labs/php-shapefile/#multilinestring__construct) constructor flags `$flag_enforce_closed_rings` to `false` and proceed to write invalid polygons to a shapefile, even though I strongly recommend you not to do such a thing...

**Comment by gasparesganga** [comment]
So? Did you have time to try my advices or have you found another solution?
Would you mind sharing it here or at least answering to my message?

**Comment by gasparesganga** [comment]
_Thank you for this fundamental contribution of yours.
It's been a real pleasure to wait for an answer that never came.
We hope to see you soon again with another 2-liner question and no follow up..._
