### ISSUE TITLE
Linestring standart

### ISSUE THREAD

**Issue by m54predator** [gasparesganga/php-shapefile#25]
You should change this constant `const GEOJSON_BASETYPE  = 'Linestring';` on LineString and `const GEOJSON_BASETYPE  = 'MultiLinestring';` too, because by geojson RFC it's not correct. 
src/Shapefile/Geometry/MultiLinestring.php
https://tools.ietf.org/html/rfc7946

**Comment by gasparesganga** [comment]
Nice catch that capital ***S***.
Good GeoJSON parsers *should* be able to deal with input in a case-insensitive fashion (this library for example is able to do that with `Geometry::initFromGeoJSON()`), nonetheless I'm fixing it right now. It's much better to comply 100% to the standard, even in such tiny details. Thanks
