### ISSUE TITLE
How to wrap generated shapefile (dbf, shp, shx) in a zip?

### ISSUE THREAD

**Issue by fauzipadlaw** [gasparesganga/php-shapefile#27]

**Comment by gasparesganga** [comment]
Using a specific library.

What has to do your question with this library? Why opening an issue here? Why not looking for the answer on Google, on PHP manual, or even asking this question in generic purpose communities (eg. stackoverflow)?
Don't get me wrong, I'm super happy people use my library, but *this* is not the right place for generic programming advices...

PS: I usually use **ZipArchive**, by the way ;)

**Comment by fauzipadlaw** [comment]
Yes I know, i thought there was a way to do that with this library. But nvm, I solved my issue. Thank you for answering :)
