### ISSUE TITLE
Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by kaylucas** [gasparesganga/php-shapefile#3]
Hi, thanks for writing this libary, it's useful to be able to work with shapefiles directly in PHP. I'm using it with PHP 5.6 and I was getting the `Assigning the return value of new by reference is deprecated` error. Removing the `&` from all instances of `=& new` in the phpxbase library fixed it for me.

**Comment by gasparesganga** [comment]
Hi. The PHPXBase library was written by **Erwin Kooi** in 2006, you can find his original source [here](http://www.phpclasses.org/package/2673-PHP-Access-dbf-foxpro-files-without-PHP-ext-.html). I have just fixed a couple of minor bugs and provided a _name-conversion_ file to be included, but the code is 99,9% as he originally released it.
Anyways, you did the right thing if you don't want to see that notice. Maybe I can review his whole library sometimes, but that's not high in my priorities _(after all, that's just a fallback library I'm using to replace native [dBase](http://php.net/manual/en/book.dbase.php) functions)_.

Thanks for using my PHP Shapefile library, I'm glad you liked it.
