### ISSUE TITLE
Open .shp without other project files present

### ISSUE THREAD

**Issue by tostercx** [gasparesganga/php-shapefile#33]
Hey,

is it possible to load a single shape file without the SHX/DBF? Currently getting an `Shapefile::ERR_FILE_EXISTS` if a .dbf isn't present in the same folder when creating a `ShapefileReader`. I read trough the options in the documentation but didn't see anything relevant.

I'm probably an edge case but I have a lot of .shp files without anything else from a legacy system that I'm upgrading.

**Comment by tostercx** [comment]
You know what, scratch that, that's out of the specification anyway.

Found out I can run the shp files trough `ogr2ogr` and it will generate dummy files for the project :)

Ty for the library btw!

**Comment by gasparesganga** [comment]
Yay, that was a quick one... from start to closed in less than 1 hour! :)

Basically you answered yourself: a shapefile is composed of *at least* 3 files: SHP, SHX and DBF. If any of these is missing, then it's an invalid shapefile.
The *dirty hack* in these cases, when you have legacy files from who-knows-where that you need to read, is generating some dummy files* exactly as you ended up doing.

* Not so dummy actually: the SHX needs to expose some valid record offsets (easily computable from the SHP assuming there are no *empty spaces* between records, something that might happen more often than not) and the DBF needs a valid empty structure as well, but it can be the same for any shapefile.

It's a controversial subject, but I might think about adding some kind of option to force the opening of shapefiles with missing base files and offering the possibility to *restore* them as well as it's possible, basically the same thing that ogr does...

**Comment by tostercx** [comment]
It's Murphy's law - as soon as I complain to someone the solution magically appears!

Spent hours before trying to understand what the other files do and how the old software could possibly work, lol.
