### ISSUE TITLE
PHP7 Support and full use of Composer

### ISSUE THREAD

**Issue by NickStallman** [gasparesganga/php-shapefile#4]
api_conversion.php seems to have a lot of =& pass by reference calls which are no longer valid with PHP7.

Additionally the bundled copy of phpxbase is probably not required if you are using composer, it can just specify phpxbase as a dependency. It looks like phpxbase has been updated somewhat since the bundled version was copied.

**Comment by gasparesganga** [comment]
I'm closing this one, please refer to the pull request #5
