### ISSUE TITLE
Multilinestring does not work

### ISSUE THREAD

**Issue by AB6162** [gasparesganga/php-shapefile#44]
Hi, I am working on a project where I have to generate some points and polylines, however when I try to assign attributes to each polylines, the attributes don't display, I need it to be just a polyline file containing the polylines with their respective information as the following example:

![image](https://user-images.githubusercontent.com/11187639/180084083-b8cabb82-2c4b-4212-9afe-c2fb19886c70.png)

Single polyline file contains multiple polylines

![image](https://user-images.githubusercontent.com/11187639/180084131-dac31e35-01db-4813-8bdf-74ca6dccbd83.png)

the code I am using is the following:

```
$fields = array();
$fields['description'] = $Shapefile->addCharField('description', 254);
$multi = array();

foreach ($polylines_arr as $key => $value) {

	$linestring = array();
        $tam_value = count($value);

	for ($j = 0; $j < $tam_value; $j++) {

		array_push($linestring, new Point($value[$j]['lon'], $value[$j]['lat']));

	}

	$temp_linestring = new Linestring($linestring);
	$temp_linestring->setData($fields['description'], 'value test field: '.mt_rand(0, 600)); **//This data is not displayed in the attribute table**

	array_push($multi, $temp_linestring);

}

$Multiline = new MultiLinestring($multi);
$Multiline->setData($fields['description'], 'close polyline'); **//Only shows this data**
$Shapefile->writeRecord($Multiline);
$Shapefile = null;
```

How can I make each polyline have its attributes and generate only one file? Currently, it only generates a single polyline, not split with its respective attributes as the graphic example I mentioned before.

Is it possible to generate the polylines separately and then **merge them**?

I would appreciate any help or guidance you can give me!

**Comment by gasparesganga** [comment]
Hi Alejandro,
I'm afraid what you are trying to do is not allowed with shapefiles.
In a shapefile, **each geometry** element of shape type, in this case  `Polyline`  (`Shapefile::SHAPE_TYPE_POLYLINE`), represents **one record**. It does not matter how it could be decomposed to simplier geometry types.
In fact, the same concept could be applied to the single `Points` that make up your individual `Linestrings`.


A possible solution is saving the `Linestrings` in your shapefile, not the `MultiLinestrings`.
Add another field, something like `multi_id` and assign the same id to all the `Linestrings` that are part of the same `MultiLinestring`. This way you will have both the single parts data and the information on what `MultiLinestring` they should be part of.

**Comment by AB6162** [comment]
Hi, I was able to solve the problem, what to do is the following when you want segments of a polyline in a single file (check the comments in code):

```
foreach ($polylines_arr as $key => $value) {

	$linestring = array();
        $tam_value = count($value);

	for ($j = 0; $j < $tam_value; $j++) {

                //Add points to a $linestring array
		array_push($linestring, new Point($value[$j]['lon'], $value[$j]['lat']));

	}

        //Create the linestring and add the field and value
	$temp_linestring = new Linestring($linestring);
	$temp_linestring->setData($fields['description'], 'field value: '.mt_rand(0, 600));
	
	//Write the linestring into the shapefile and continue with the next polyline without close the shapefile
	$Shapefile->writeRecord($temp_linestring);

}

//Close the shapefile
$Shapefile = null;
```

This generates a single file with several polylines, each with its own attributes.

**Comment by gasparesganga** [comment]
Yep, that's exactly what I was suggesting: storing single `Linestrings` instead or `MultiLinestrings`.

I'm glad it worked for you ;)
