### ISSUE TITLE
Error during reading date from DBF file

### ISSUE THREAD

**Issue by Nordok** [gasparesganga/php-shapefile#47]
Hey! While trying to fetch record from a shape file like it shown in the docs, I've got an error:
`In ShapefileReader.php line 524: Warning: Trying to access array offset on value of type bool`

https://github.com/gasparesganga/php-shapefile/blob/f9cb849fb39be5aaec816505caf27452deecf458/src/Shapefile/ShapefileReader.php#L524

Shouldn't this line looks like:
`if ($errors && ($errors['warning_count'] || $errors['error_count'])) {`

Because according to the PHP docs `\DateTime::getLastErrors()` method can also return `false` in case of no errors.

My code:
```
$path = $this->pathResolver->resolve(
            'ukr_admbnda_adm0_sspe_20221005.shp',
            'var/locations/extracted'
        );

        $shapeFile = new ShapefileReader($path);
        
        $shape = $shapeFile->fetchRecord();
```

And if it will help, I'm trying to read this dataset

https://data.humdata.org/dataset/cod-ab-ukr (ukr_adm_sspe_20221005.zip)

**Comment by gasparesganga** [comment]
It seems it depends on PHP version: PHP 8 is way more strict when it comes to type juggling and checks.

I am patching this in current codebase.
I will release a final v3.x release soon and move on to v4, which will drop support for older PHP versions, making maintainance way easier.

Thank you!

**Comment by EriksRudzitis** [comment]
@gasparesganga Any news of v4 realease? Iam having the same issue
