### ISSUE TITLE
Error during looping through shapefile

### ISSUE THREAD

**Issue by lytrieu002** [gasparesganga/php-shapefile#49]
Hi! While trying to fetch record from a shape file, I've got an error when fetch the last record. Specifically, the last record will be skipped and not read.
For example, I have a shapefile which has 100 records. Each record has Field name "ID" start from 1 to 100. When looping through all record, It will show the result below.
```
$Shapefile = new \Shapefile\ShapefileReader($basePath, [\Shapefile\Shapefile::OPTION_POLYGON_CLOSED_RINGS_ACTION => false, \Shapefile\Shapefile::OPTION_DBF_NULL_PADDING_CHAR => ']);
$tot = $Shapefile->getTotRecords();
for ($i = 1; $i <= $tot; $i++) {
    $Shapefile->setCurrentRecord($i);
    $Geometry = $Shapefile->fetchRecord();
    if ($Geometry->isDeleted()) {
            echo 'Deleted!<br>';
            continue;
    }
    $myID = $Geometry->getData('ID');
    echo 'i = ' . $i .  ' - ID = ' . $myID . '<br>';
}
```
Result:
```
i = 1 - ID = 1
i = 2 - ID = 2
...
i = 97 - ID = 97
i = 98 - ID = 98
i = 99 - ID = 99
```
As you can see, the record with ID 100 does not show.
I also debug and found that the line code ShapefileReader.php#L460 will error when fetch the last record.
https://github.com/gasparesganga/php-shapefile/blob/f9cb849fb39be5aaec816505caf27452deecf458/src/Shapefile/ShapefileReader.php#L460

**Comment by gasparesganga** [comment]
Hi.

This is usually due to corrupted shapefiles that don't comply to the specs. It might be truncated or missing some bytes.
When you write:
> it will error when fetch the last record.

what do you mean? What error does it return? Do you have any `try...catch` block in place? If so, what [ShapefileException error type](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefileexception) do you get? It tends to give you a pretty detailed description of the issue with your specific shapefile.

A simple boilerplate:

```php
try {
    /* Your code here */
} catch (ShapefileException $e) {
    // Print detailed error information
    echo "Error Type: " . $e->getErrorType()
        . "\nMessage: " . $e->getMessage()
        . "\nDetails: " . $e->getDetails();
}
```
One additional quick note: why are you setting `Shapefile::OPTION_POLYGON_CLOSED_RINGS_ACTION` constructor option to `false`? This parameter is **not** boolean, it rather accepts 3 possible values:
- `Shapefile::ACTION_IGNORE`
- `Shapefile::ACTION_CHECK`
- `Shapefile::ACTION_FORCE`

Please check [ShapefileReader construct](https://gasparesganga.com/labs/php-shapefile/#shapefilereader__construct) and [Polygon construct](https://gasparesganga.com/labs/php-shapefile/#polygon__construct) in the official documentation for reference.

**Comment by lytrieu002** [comment]
Thank you for your reply.
I tried to put my loop inside try catch below:
```
try {
	for ($i = 65700; $i <= $tot; $i++) {
		$Shapefile->setCurrentRecord($i);
		$Geometry = $Shapefile->fetchRecord();
		if ($Geometry->isDeleted()) {
				echo 'Deleted!<br>';
				continue;
		}
		$myID = $Geometry->getData('CAPDORR');
		echo 'i = ' . $i .  ' - CAPDORR = ' . $myID . '<br>';
	}
} catch (ShapefileException $e) {
	// Print detailed error information
	echo "Error Type: " . $e->getErrorType()
		. "\nMessage: " . $e->getMessage()
		. "\nDetails: " . $e->getDetails();
}
```
The result is the same, no error return. $i still count to 65706 instead of 65707 (total records of shapefile).
```
i = 65700 - CAPDORR = 0
i = 65701 - CAPDORR = 0
i = 65702 - CAPDORR = 0
i = 65703 - CAPDORR = 0
i = 65704 - CAPDORR = 0
i = 65705 - CAPDORR = 0
i = 65706 - CAPDORR = 0
```
When I turn on debug mode and debug display on wordpress, I received the below error. 
```
Warning: unpack(): Type d: not enough input, need 8, have 0 in C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php on line 312

Fatal error: Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php:312 Stack trace: #0 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(312): current(false) #1 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(645): Shapefile\ShapefileReader->readDoubleL('shp') #2 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(898): Shapefile\ShapefileReader->readMRange() #3 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(960): Shapefile\ShapefileReader->readPolyLineZ(false) #4 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(461): Shapefile\ShapefileReader->readPolygonZ() #5 C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php(241): Shapefile\ShapefileReader->readCurrentRecord() #6 C:\LinkToMyWebsite\wp-content\themes\gistheme\functions.php(1414): Shapefile\ShapefileReader->fetchRecord() #7 C:\LinkToMyWebsite\wp-includes\shortcodes.php(355): submission_solieu_new_func('', '', 'show_table') #8 [internal function]: do_shortcode_tag(Array) #9 C:\LinkToMyWebsite\wp-includes\shortcodes.php(227): preg_replace_callback('/\\[(\\[?)(wpcfu_...', 'do_shortcode_ta...', '<p>[wpcfu_form]...') #10 C:\LinkToMyWebsite\wp-includes\class-wp-hook.php(308): do_shortcode('<p>[wpcfu_form]...') #11 C:\LinkToMyWebsite\wp-includes\plugin.php(205): WP_Hook->apply_filters('<p>[wpcfu_form]...', Array) #12 C:\LinkToMyWebsite\wp-includes\post-template.php(255): apply_filters('the_content', '[wpcfu_form]\r\n[...') #13 C:\LinkToMyWebsite\wp-content\themes\gistheme\template-parts\content\content-page.php(29): the_content() #14 C:\LinkToMyWebsite\wp-includes\template.php(785): require('C:\\WebGIS-OpenS...') #15 C:\LinkToMyWebsite\wp-includes\template.php(718): load_template('C:\\WebGIS-OpenS...', false, Array) #16 C:\LinkToMyWebsite\wp-includes\general-template.php(204): locate_template(Array, true, false, Array) #17 C:\LinkToMyWebsite\wp-content\themes\gistheme\page.php(17): get_template_part('template-parts/...') #18 C:\LinkToMyWebsite\wp-includes\template-loader.php(106): include('C:\\WebGIS-OpenS...') #19 C:\LinkToMyWebsite\wp-blog-header.php(19): require_once('C:\\WebGIS-OpenS...') #20 C:\LinkToMyWebsite\index.php(17): require('C:\\WebGIS-OpenS...') #21 {main} thrown in C:\LinkToMyWebsite\wp-content\themes\gistheme\vendor\php-shapefile\src\Shapefile\ShapefileReader.php on line 312
```

btw, thanks for your note, I changed my code to
```
$Shapefile = new \Shapefile\ShapefileReader($basePath, 
            [\Shapefile\Shapefile::OPTION_POLYGON_CLOSED_RINGS_ACTION => \Shapefile\Shapefile::ACTION_FORCE,
            \Shapefile\Shapefile::OPTION_DBF_NULL_PADDING_CHAR => ''
            ]);
```

**Comment by gasparesganga** [comment]
Yep, this looks like a corrupted shapefile with missing bytes at the end.
Unfortunately, this is not uncommon, especially with Z type shapefiles: lately I've received many reports from users dealing with malformed shapefiles like that. I suspect some kind of GIS software out there in the wild got the specs wrong and is producing them.

Feel free to share that shapefile with me (even via email if you don't want/cannot share it here, you can find my address on the official documentation page): I will look into it to confirm that and of course I will treat it with extreme confidentiality and delete right after.

**Comment by lytrieu002** [comment]
You can download and check the shapefile at [This link](https://warec.vn/wp-content/uploads/calculatedMap.zip)

**Comment by gasparesganga** [comment]
This shapefile has 65706 records!
Where are you getting that 65707 from?
Check the output of `$Shapefile->getTotRecords()`

Now you are confusing me: those errors and warnings you pasted here are clearly not from the same shapefile you linked. Are you sure you are using the latest version of the library (v3.4.0)?
Even if tou try to pass a non-existent record to `$Shapefile->setCurrentRecord()` the library will raise a  `ERR_INPUT_RECORD_NOT_FOUND` `ShapefileException`.

You can easily check that everything works fine like that:
```php
try {
    // Set last record as current
    $Shapefile->setCurrentRecord($Shapefile->getTotRecords());
    
    $Geometry = $Shapefile->fetchRecord();
    if ($Geometry->isDeleted()) {
        echo "DELETED";
    } else {
        echo "\nWKT: ";
        print_r($Geometry->getWKT());
        
        echo "\nDBF: ";
        print_r($Geometry->getDataArray());
    }

} catch (ShapefileException $e) {
    // Print detailed error information
    echo "Error Type: " . $e->getErrorType()
        . "\nMessage: " . $e->getMessage()
        . "\nDetails: " . $e->getDetails();
}
```

Also, in order to avoid possible bogus mistakes with counters and whatnot, you can rely on a `while` block to loop over all the records, the library takes care of internal record pointer:
```php
while ($Geometry = $Shapefile->fetchRecord()) {
    /* Here it will loop through all the records */
}
```

**Comment by lytrieu002** [comment]
Sorry for my mistake. I gave you a calculated shapefile, which was proccessed by php-shapefile so that It contains only 65706 records.

This base shapefile with total 65707 records ($Shapefile->getTotRecords()), please down load [here](https://warec.vn/wp-content/uploads/baseMap.zip)

**Comment by gasparesganga** [comment]
It's the same issue with corrupted shapefiles people are having here: #38 

Unfortunately there's not much I can do if a shapefile is broken.
As I stated before, it looks like some wild software out there is spitting out incomplete shapefiles these days...

I have a brand new version in the pipeline and I could think about adding some costructor option to avoid the warnings, but the truth is that some data loss for Z and M dimensions of the last record will be there. I'm not a fan of having a way to encourage corrupted shapefiles and explicit data loss...

Everything I wrote in the other issue applies to your case: you can use my library to *recover* the shapefile (consider using `Shapefile::OPTION_POLYGON_CLOSED_RINGS_ACTION => Shapefile::ACTION_FORCE` as well!), bearing in mind that you can either skip that last record or accepting some information will be lost (to be honest, it looks like your shapefile could have been a *Polygon* one without any Z nor M dimension, not sure why it's a *PolygonZ* in the first place!)

**Comment by lytrieu002** [comment]
I have tried to recover baseMap by your code here https://github.com/gasparesganga/php-shapefile/issues/38#issuecomment-828625021
However, the total record after recover still 65706 and of course `echo 'DONE!';` not be executed.
I used "Fix Geometries" tool in QGIS and exported this baseMap. May be I will use ArcGIS instead to check if this problem still happens.

**Comment by lytrieu002** [comment]
Hi. I dropped Z/M values by QGIS and now shapefile can be read all the record. The new shapefile type is POLYGON instead of POLYGONZ. This also reduce file size from 190MB to 130MB. Many thanks for your help. 
Btw, the total time to write a shape file which has 65707 records take about 3 minutes. Could you please tell me some advices to improve it? I tried to set `Shapefile::OPTION_BUFFERED_RECORDS` some values (100/500/1000/5000) but nothing much change. In QGIS, I only need ~10s to save the shapefile.

**Comment by gasparesganga** [comment]
I'm glad you fixed it.
As I wrote before, QGIS (and/or other GIS software) is being producing some malformed Z shapefiles for a while, that's a shame!

About the performance: if `Shapefile::OPTION_BUFFERED_RECORDS` then it might depend on your server HW or PHP settings.
~3min for 65k records is not too bad after all. Keep in mind that this library is a totally different animal compared to desktop GIS software.
Next release will include a `FileInterface` (you can already find a working draft in the master branch, not yet released) that will allow drastic improvements using in-memory streams.
