### ISSUE TITLE
Trouble migration PHP7 to PHP8

### ISSUE THREAD

**Issue by epointal** [gasparesganga/php-shapefile#51]
With **ShapefileReader**:

`Message: 'Return type of Shapefile\ShapefileReader::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`'

**Comment by are27** [comment]
Seeing the same #[\ReturnTypeWillChange] issue with php 8.1
Is a fix planned or should an alternate implementation be considered?

**Comment by gasparesganga** [comment]
Yep, it's a trivial fix indeed, adding that `#[\ReturnTypeWillChange]`.
I wanted to make things in a clean way and split the development into some v3 and v4 branches, but I've been too busy for a long time and this wasn't high in the priority list.

For the next few weeks you can apply this trivial *patch* yourself, I will release a fully PHP8.2 compatible v3 version and in the meanwhile switch active development onto v4.

**Comment by epointal** [comment]
Thinks

**Comment by epointal** [comment]
Thanks
