### ISSUE TITLE
Comparision on write SHP always false

### ISSUE THREAD

**Issue by MTakashiMori** [gasparesganga/php-shapefile#54]
Hi @gasparesganga, first of all, thanks for the awesome lib and support. I see that you actively help us out.

My issue is related to creating a new SHP file. Is always throwing this exception ( on line https://github.com/gasparesganga/php-shapefile/blob/v3.4.0/src/Shapefile/Shapefile.php#L836 )
> ShapefileException(Shapefile::ERR_FILE_EXISTS, $files[$type])

I'm using PHP 7.3,
And the Version 3.40

After reading the docs and the open issues, I started debugging the class Shapefile.php

And I believe that there is a missing comparison of lines
https://github.com/gasparesganga/php-shapefile/blob/v3.4.0/src/Shapefile/Shapefile.php#L826-L827

Specifically on the condition 
` $this->getOption(Shapefile::OPTION_EXISTING_FILES_MODE) !== Shapefile::MODE_PRESERVE`
Because this will always get us a 0 != 0

I also believe that this is wrong because if this condition should be false ( as declared ), the check  
> is_readable($files[$type]),
> is_file($files[$type]),

should be both false, which don't make sense if we want to write over this shape

I tried to load a zip with all shape files(SHP, SHX, DBF, DBT, PRJ, CPG) and the shape separately.

> $file = storage_path('tmp/shape/shape.shp');
> // $file = storage_path('tmp/shape/shape2.zip');

The shapefile is valid and working.
All these conditions below are true 

> is_string($files[$type]) => true,
> is_writable(dirname($files[$type])) => true,
> file_exists($files[$type]) => true,
> is_readable($files[$type]) => true,
> is_file($files[$type]) => true,

Here is the complete code:
https://github.com/gasparesganga/php-shapefile/blob/v3.4.0/src/Shapefile/Shapefile.php#L813-L840

Thanks in advise for everthing

**Comment by gasparesganga** [comment]
Hi! Thank you for your feedback, I appreciate it.
Unfortunately I have been very busy with my working schedule during the last few months and all the planned upgrades have been delayed. I will continue to maintain and improve this project anyways.

Now, onto your question:
I cannot see the issue to be honest. That condition is checking whether you want to preserve, append or overwrite an eventually existing shapefile, based on the value of `Shapefile::OPTION_EXISTING_FILES_MODE` constructor option.
More specifically, if the you want to preserve the file, it ensures no other file exists in the same directory with the same name, otherwise it checks if you have the right permissions on it.

Why would you always get a `0 != 0`?

Can you provide some example code of yours that is causing the issue so that I can reproduce it?

**Comment by MTakashiMori** [comment]
Hey @gasparesganga, thanks for the quick reply.

So, your comment helped me out on figuring the issue.

- I was trying to keep a raw .zip file on my storage, to get it overwritten on the run, then downloaded.
- I assumed that this should be the correct implementation since on the docs (https://gasparesganga.com/labs/php-shapefile/) in the section "Writing Shapefiles", your code shows the class opening a shapefile.

- The issue happened when I tried to open the file and I was getting the error "Check if the file exists and is readable and/or writable"

The solution (using the Gaspar comment) checking the _constructor on the ShapefileWriter class, it loads some options preset, but we can overwrite it using :

> $file = storage_path('tmp/shape/ex_shape');
> $Shapefile = new ShapefileWriter($file, [
>     'OPTION_EXISTING_FILES_MODE' => 1 
> ]);


@gasparesganga, I believe that this is worth a note on the docs, I can make if if you want.

But thanks for all the help in solving this one. My shape is now working fine and smooth.

Bests, Marcelo.

**Comment by gasparesganga** [comment]
This library cannot read/write zipfiles, it only operates on shapefiles (`.shp`, `.shx`, `.dbf`, `.prj`, `.dbt`, `.cpg`). PHP provides enough capabilities to deal with zilfiles on its own and there are tons of other libraries out there just in case.

About the constructor option, I **strongly** advise on using class constants and not scalar values (they might change in the future, while constants names will not). In your case, if you want to overwrite any existing shapefile, **`Shapefile::MODE_OVERWRITE`**:
```php
$ShapefileWriter= new ShapefileWriter($file, [
    Shapefile::OPTION_EXISTING_FILES_MODE => Shapefile::MODE_OVERWRITE,
]);
```

Thank you for your offer but there is already a note about that in the docs, under [ShapefileWriter::__construct](https://gasparesganga.com/labs/php-shapefile/#shapefilewriter__construct). Scroll down through the options to `Shapefile::OPTION_EXISTING_FILES_MODE` and you will find it.
Do you think that is not enough and/or clear enough? Writing good documentation is the worst part of the whole process...

**Comment by MTakashiMori** [comment]
@gasparesganga, thanks for all the advice. I can confirm that my issue is solved.

I could avoid all of this by just reading the documentation better. I believe that is all clear, no need to enhance more.

Bests, Marcelo.

Ps. If you need any help with the docs, or have enhancements requests, please, let me know.
