### ISSUE TITLE
Get PRJ returns empty when trying to write a Shapefile, SHP, DBF and SHX files also  returning invalid despite having proper file sizes

### ISSUE THREAD

**Issue by AntonioA-D-C** [gasparesganga/php-shapefile#56]
I'm trying to convert my database data into a Shapefile utilizing this package in laravel.

The goal is to generate the shapefile and downloading it, so far, I'm not having a lot of success, I've managed to properly generate the zip file and I've also managed to see that SHP, DBF and SHX files do contain data evident from the file size, however when I try to open it utilizing SHP opener programs it says data is invalid.

PRJ files are a different issue altogether, with the other files I'm at least able to see them and see their filesize, but PRJ ALWAYS returns zero bytes with no exceptions, and I haven't found a way to generate it.

![image](https://github.com/gasparesganga/php-shapefile/assets/67211786/62bb53db-0128-4251-ba34-26a808600c65)

My code in Laravel

`

    public function downloadShapeFile(Request $request)
    {
        $returnUrl = 'dashboard';
        $showModal = true;

        try {
            if ($request->filter == 0) {
                $points = punto::whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
            } else {
                $points = punto::where('DepartamentoID', '=',  $request->deptType)->whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
            }
            $allPoints = PuntoResource::collection($points);
         
            //$Shapefile = new Shapefile('output.shp', Shapefile::SHAPE_TYPE_POINT);
            $shapefilePath = public_path('storage\shapefile\POINT');
        $Shapefile = new ShapefileWriter($shapefilePath, [
            Shapefile::OPTION_DBF_FORCE_ALL_CAPS        => true,
            Shapefile::OPTION_DBF_NULL_PADDING_CHAR     => '*',
            Shapefile::OPTION_EXISTING_FILES_MODE       => Shapefile::MODE_OVERWRITE,
            Shapefile::FILE_PRJ=> fopen($shapefilePath.".prj", 'c+b'),
            Shapefile::FILE_SHP => fopen($shapefilePath.'.shp', 'c+b'),
            Shapefile::FILE_SHX => fopen($shapefilePath.'.shx', 'c+b'),
            Shapefile::FILE_DBF => fopen($shapefilePath.'.dbf', 'c+b'),
        ]);
        
         $Shapefile->setShapeType(Shapefile::SHAPE_TYPE_POINT);
        //    $coords = array();
            foreach ($allPoints as $rows) {

                $coordinates = $this->transformCoordinates($rows["Latitud"],$rows["Longitud"]);
                $point = new Point($coordinates["easting"], $coordinates["northing"]);
             
                $point->setData('id', $rows['puntoID']);
                
                $Shapefile->writeRecord($point);
             
             }
             $Shapefile->getPRJ();
         
           
             // Set the appropriate headers for the download

             $zip = new ZipArchive();
             $zipFileName = 'POINT_shapefile.zip';
             $zipFilePath = public_path('storage/shapefile/' . $zipFileName);
     
             if ($zip->open($zipFilePath, ZipArchive::CREATE) === true) {
                 // Add Shapefile files to the ZIP archive
                 $zip->addFile($shapefilePath . '.shp', 'POINT.shp');
                 $zip->addFile($shapefilePath . '.shx', 'POINT.shx');
                 $zip->addFile($shapefilePath . '.dbf', 'POINT.dbf');
                 $zip->addFile($shapefilePath . '.prj', 'POINT.prj');
                 // Add more files if needed
     
                 $zip->close();
             }
             $Shapefile= null;
             // Set the appropriate headers for the download
             
             return response()->download($zipFilePath)->deleteFileAfterSend(true);
     
             

        } catch (\Exception $e) {
            dd($e);
            return view('modals.failure', ['showModal' => $showModal, 'returnUrl' => $returnUrl]);
            return redirect()->back()->with('error', 'Error exporting data');
        }
    }
`

What's stopping me from generating the appropriate files without issue/generating proper SHP/DBF/SHX files as well as generating a PRJ file?

**Comment by gasparesganga** [comment]
Hi Antonio,

I can see two obvious issues with your code:

1. You are making some confusion with file handlers.
Please have a look at the [ShapefileWriter::__construct](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilewriter) signature: if you want to manually open file handles and pass them to the library, you should use an array as first parameter. You can find more details in the [Files and filenames](https://gasparesganga.com/labs/php-shapefile/#files-and-filenames) section.
Anyways, judging from that code you pasted here, I cannot see the reason why you wouldn't let the library deal with file opening, which is basically what it is doing right now since it is ignoring the resource handles you are passing as *options* ;)
Now, is this the cause if corrupted/incomplete shapefiles? No, it's not...
The problem is that you are adding the files to the Zip **before** finalizing the shapefile! You simply need to call `$Shapefile = null;` before.


2. The PRJ is empty because you are never writing anything into it :)
`Shapefile::getPRJ()` is used to **get** the contents of the PRJ file. On the other hand, to write it, you should use [ShapefileWriter::setPRJ()](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilewriter)


To recap, here you are the revised code that should work as expected. I haven't tested it, but you get the idea:

```php
public function downloadShapeFile(Request $request)
{
    $returnUrl = 'dashboard';
    $showModal = true;

    try {
        if ($request->filter === 0) {
            $points = punto::whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
        } else {
            $points = punto::where('DepartamentoID', '=',  $request->deptType)->whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
        }
        $allPoints = PuntoResource::collection($points);
        
        $shapefilePath = public_path('storage/shapefile/POINT');
        $Shapefile = new ShapefileWriter($shapefilePath, [
            Shapefile::OPTION_DBF_FORCE_ALL_CAPS    => true,
            Shapefile::OPTION_DBF_NULL_PADDING_CHAR => '*',
            Shapefile::OPTION_EXISTING_FILES_MODE   => Shapefile::MODE_OVERWRITE,
        ]);
        
        $Shapefile->setShapeType(Shapefile::SHAPE_TYPE_POINT);
        foreach ($allPoints as $rows) {
            $coordinates = $this->transformCoordinates($rows["Latitud"],$rows["Longitud"]);
            $point = new Point($coordinates["easting"], $coordinates["northing"]);
            $point->setData('id', $rows['puntoID']);
            $Shapefile->writeRecord($point);

        }
        
        // Set PRJ contents
        $Shapefile->setPRJ("Your PRJ file contents here...");
        
        // Close the Shapefile BEFORE adding it to the Zip
        $Shapefile = null;
        
        // Create the Zip
        $zip = new ZipArchive();
        $zipFileName = 'POINT_shapefile.zip';
        $zipFilePath = public_path('storage/shapefile/' . $zipFileName);
        
        if ($zip->open($zipFilePath, ZipArchive::CREATE) === true) {
            // Add Shapefile files to the ZIP archive
            foreach (['shp', 'shx', 'dbf', 'prj'] as $ext) {
                $zip->addFile("$shapefilePath.$ext", basename("$shapefilePath.$ext"));
            }
            // Add more files if needed
            $zip->close();
        }
        
        // Set the appropriate headers for the download
        return response()->download($zipFilePath)->deleteFileAfterSend(true);
        
    } catch (\Exception $e) {
        dd($e);
        return view('modals.failure', ['showModal' => $showModal, 'returnUrl' => $returnUrl]);
        return redirect()->back()->with('error', 'Error exporting data');
    }
}
```

Cheers

**Comment by AntonioA-D-C** [comment]
> Hi Antonio,
> 
> I can see two obvious issues with your code:
> 
> 1. You are making some confusion with file handlers.
>    Please have a look at the [ShapefileWriter::__construct](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilewriter) signature: if you want to manually open file handles and pass them to the library, you should use an array as first parameter. You can find more details in the [Files and filenames](https://gasparesganga.com/labs/php-shapefile/#files-and-filenames) section.
>    Anyways, judging from that code you pasted here, I cannot see the reason why you wouldn't let the library deal with file opening, which is basically what it is doing right now since it is ignoring the resource handles you are passing as _options_ ;)
>    Now, is this the cause if corrupted/incomplete shapefiles? No, it's not...
>    The problem is that you are adding the files to the Zip **before** finalizing the shapefile! You simply need to call `$Shapefile = null;` before.
> 2. The PRJ is empty because you are never writing anything into it :)
>    `Shapefile::getPRJ()` is used to **get** the contents of the PRJ file. On the other hand, to write it, you should use [ShapefileWriter::setPRJ()](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilewriter)
> 
> To recap, here you are the revised code that should work as expected. I haven't tested it, but you get the idea:
> 
> ```
> public function downloadShapeFile(Request $request)
> {
>     $returnUrl = 'dashboard';
>     $showModal = true;
> 
>     try {
>         if ($request->filter === 0) {
>             $points = punto::whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
>         } else {
>             $points = punto::where('DepartamentoID', '=',  $request->deptType)->whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
>         }
>         $allPoints = PuntoResource::collection($points);
>         
>         $shapefilePath = public_path('storage/shapefile/POINT');
>         $Shapefile = new ShapefileWriter($shapefilePath, [
>             Shapefile::OPTION_DBF_FORCE_ALL_CAPS    => true,
>             Shapefile::OPTION_DBF_NULL_PADDING_CHAR => '*',
>             Shapefile::OPTION_EXISTING_FILES_MODE   => Shapefile::MODE_OVERWRITE,
>         ]);
>         
>         $Shapefile->setShapeType(Shapefile::SHAPE_TYPE_POINT);
>         foreach ($allPoints as $rows) {
>             $coordinates = $this->transformCoordinates($rows["Latitud"],$rows["Longitud"]);
>             $point = new Point($coordinates["easting"], $coordinates["northing"]);
>             $point->setData('id', $rows['puntoID']);
>             $Shapefile->writeRecord($point);
> 
>         }
>         
>         // Set PRJ contents
>         $Shapefile->setPRJ("Your PRJ file contents here...");
>         
>         // Close the Shapefile BEFORE adding it to the Zip
>         $Shapefile = null;
>         
>         // Create the Zip
>         $zip = new ZipArchive();
>         $zipFileName = 'POINT_shapefile.zip';
>         $zipFilePath = public_path('storage/shapefile/' . $zipFileName);
>         
>         if ($zip->open($zipFilePath, ZipArchive::CREATE) === true) {
>             // Add Shapefile files to the ZIP archive
>             foreach (['shp', 'shx', 'dbf', 'prj'] as $ext) {
>                 $zip->addFile("$shapefilePath.$ext", basename("$shapefilePath.$ext"));
>             }
>             // Add more files if needed
>             $zip->close();
>         }
>         
>         // Set the appropriate headers for the download
>         return response()->download($zipFilePath)->deleteFileAfterSend(true);
>         
>     } catch (\Exception $e) {
>         dd($e);
>         return view('modals.failure', ['showModal' => $showModal, 'returnUrl' => $returnUrl]);
>         return redirect()->back()->with('error', 'Error exporting data');
>     }
> }
> ```
> 
> Cheers

Thank you for the suggestion, I fixed my previous issue and can confirm I currently have no problems with the DBF and PRJ files, they're working as intended.

However, SHP and SHX are still weird, I still can't load the shapefile properly thanks to those two files, what should I do?

Code: 
```

  public function downloadShapeFile(Request $request)
    {
        $returnUrl = 'dashboard';
        $showModal = true;
    
        try {
            if ($request->filter === 0) {
                $points = punto::whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
            } else {
                $points = punto::where('DepartamentoID', '=',  $request->deptType)->whereBetween('date', [$request->from, $request->to])->orderBy('date', 'desc')->get();
            }
            $allPoints = PuntoResource::collection($points);
            
            $shapefilePath = public_path('storage\shapefile\POINT');
            $Shapefile = new ShapefileWriter($shapefilePath, [
                Shapefile::OPTION_DBF_FORCE_ALL_CAPS    => true,
                Shapefile::OPTION_DBF_NULL_PADDING_CHAR => '*',
                Shapefile::OPTION_EXISTING_FILES_MODE   => Shapefile::MODE_OVERWRITE,
            ]);
            
            $Shapefile->setShapeType(Shapefile::SHAPE_TYPE_POINT);

           
            $Shapefile->addCharField('Descrip', 254); // Character field
            $Shapefile->addCharField('Estado', 254); // Character field
            $Shapefile->addCharField('Dpto', 254); // Character field
            $Shapefile->addCharField('Material', 254); // Character field
            $Shapefile->addFloatField('Prof',  254, 10); // Numeric field
            $Shapefile->addFloatField('Diametro', 254, 10); // Numeric field
            $Shapefile->addCharField('Codigo',  254); // Character field
            $Shapefile->addCharField('Ubicacion', 254); // Character field
            $Shapefile->addDateField('Fecha'); // Date field
            $Shapefile->addFloatField('Dist', 254, 10); // Numeric field
            $Shapefile->addCharField('Brig' , 254 ); // Character field
            $Shapefile->addCharField('Esquin-Esq', 254); // Character field
            // Add more fields as needed
    
            // Open the shapefile for writing
           
            foreach ($allPoints as $rows) {
                
                $coordinates = $this->transformCoordinates($rows["Latitud"],$rows["Longitud"]);
                $point = new Point($coordinates["easting"], $coordinates["northing"]);
                $point->setDataArray([
                    'Descrip'    => $rows["Descripcion"] ?? '-',
                    'Estado'     => $rows->estado->NombreEstado ?? '-',
                    'Dpto'       => $rows->departamento->NombreDepartamento ?? '-',
                    'Material'   => $rows->materialName->NombreMaterial ?? "-",
                    'Prof'       => $rows["profundidad"] ?? '-',
                    'Diametro'   => $rows["diameter"] ?? '-',
                    'Codigo'     => $rows["faultCode"] ?? '-',
                    'Ubicacion'  => $rows["lineLocation"] ?? '-',
                    'Fecha'      => date('Y-m-d', strtotime($rows["date"])) ?? '',
                    'Dist'       => $rows["distanciaconten"] ?? '-',
                    'Brig'       => $rows["nombrebrigadista"] ?? '-',
                    'Esquin-Esq' => $rows["esquinero_code"] ?? '-',
                ]);
          
                $Shapefile->writeRecord($point);
    
            }
            
            // Set PRJ contents
            $prjContent="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]]";
            $Shapefile->setPRJ($prjContent);
           
            // Close the Shapefile BEFORE adding it to the Zip
            $Shapefile = null;
            
            // Create the Zip
     
       $zip = new ZipArchive();
                 $zipFileName = 'POINT_shapefile.zip';
                 $zipFilePath = public_path('storage\shapefile' . $zipFileName);
         
                 if ($zip->open($zipFilePath, ZipArchive::CREATE) === true) {
                     // Add Shapefile files to the ZIP archive

                     foreach(['shp','shx', 'dbf', 'prj'] as $ext){
                        try{
                        $zip->addFile("$shapefilePath.$ext", basename("$shapefilePath.$ext"));
                        } catch(\Exception $e){
                            dd($e, "$shapefilePath.$ext", basename("$shapefilePath.$ext") );
                        }
                     }
                    
                     // Add more files if needed
         
                     $zip->close();
                 }
               
            
            // Set the appropriate headers for the download
            return response()->download($zipFilePath)->deleteFileAfterSend(true);
            
        } catch (\Exception $e) {
            dd($e);
            return view('modals.failure', ['showModal' => $showModal, 'returnUrl' => $returnUrl]);
            return redirect()->back()->with('error', 'Error exporting data');
        }
    }
```

**Comment by gasparesganga** [comment]
What do you mean with *SHP and SHX are still weird*? Do they look incomplete/truncated?
Have you tried downloading the newly created files manually, ie. without adding to a zipfile, in order to check whether the issue is within the zip itself?
I don't know your environment, but I suspect it might be related to files not yet written/finalized on disk before the zip library tries to read them (are you on Windows?)...

Por cierto, ya que hay estoy bastante seguro de que **NO** se trate de ningún bug sino de un problema de programación específico de tu código (puedo asegurarte que mi librería funciona bien, cada día la usan muchas personas y empresas privadas y públicas), podemos escribir en Español sin problemas, yo lo hablo igual de mal que el inglés  :))
Siempre intento ayudar a los usuarios, aunque ésta parece más una pregunta para comunidades como StackOverflow...

Lo que tendrías que hacer es descargar los archivos SHP y SHX sin aggregarlos a un zip, muy probablemente el problema está ahí.
Tambíen, imagino que tienes `error_reporting(E_ALL);` activado y que en el log de PHP no haya ningún mensaje ni warning, verdad? ;)

**Comment by gasparesganga** [comment]
So?

Was this a *fix my code and I'll disappear without even thanking you or telling whether it did work in the end or not* case?

Así valoras el tiempo que dediqué en leer tu código, encontrar posibles fallos, escribir una versión correcta y contestarte, DOS veces?

**Comment by AntonioA-D-C** [comment]
@gasparesganga  Yes it's fixed thank you, forgot to reply

The problem wasn't the package after all but sending the data
