### ISSUE TITLE
ShapeFile's __destruct won't close dbf file

### ISSUE THREAD

**Issue by mkedo** [gasparesganga/php-shapefile#6]
When dbase_\* extenstsion is not installed $this->dbf_handle gets int(0) as a resource pointer.
The __destruct method then assumes dbf file is already closed and won't close it.

The __destruct method may look like this:

`
 public function __destruct()
    {
        if ($this->shp_handle !== false) {
            fclose($this->shp_handle);
            $this->shp_handle = false;
        }
        if ($this->dbf_handle !== false) {
            dbase_close($this->dbf_handle);
            $this->dbf_handle = false;
        }
    }
`

**Comment by gasparesganga** [comment]
I will look into it with the upcoming new version, upgrading the xbase functions to be PHP7 compatible.

**Comment by gasparesganga** [comment]
Here you go, v2.0.0 is out now! It doesn't rely on dbase or XBase anymore, but include native DBF reading capabilities. It is 100% PHP 7 compatible and even PSR-1, PSR-2 and PSR-4 compliant.
No more dbase related issues!
