### ISSUE TITLE
 expanded borders

### ISSUE THREAD

**Issue by lemesdaniel** [gasparesganga/php-shapefile#60]
Hello,

I was studying this library and I couldn't find if there is any way for me to open a shapefile and add 10 meters to its border, generating a new shapefile with the expanded borders.

**Comment by gasparesganga** [comment]
Hi.
Geometry manipulation is out of the scope of this library.
You can use this library to read the shapefile (*ShapefileReader*), then an external library or tool ( *eg: PostGIS or SpatiaLite ST_Buffer()* ) and finally this library again to write a new modified shapefile (*ShapefileWriter*).

If your question is just about the **BoundingBox**, meaning you want to set a custom BBox for the shapefile **without** actually modifying its geometries, then you can use this library method [ShapefileWriter::setCustomBoundingBox](https://gasparesganga.com/labs/php-shapefile/#class-shapefileshapefilewriter).

**Comment by gasparesganga** [comment]
You are welcome...........
