### ISSUE TITLE
Reading shape files with ETRS89_UTM_zone_32N

### ISSUE THREAD

**Issue by jlai79** [gasparesganga/php-shapefile#61]
I mostly get shape files to import that are in ETRS89. But more and more frequently I get files with ETRS89_UTM_zone_32N.
How can I read these files with php-shapefile?

I currently use QGIS to convert the files from one format to another before importing to my software with php-shapefile.

**Comment by jlai79** [comment]
I found a solution by myself and don't think it's an issue of php-shapefile. I solved the problem by using proj4php to convert from ETRS89_UTM_zone_32N to ETRS89. Is there another recommended solution?

**Comment by gasparesganga** [comment]
Hi!
This has nothing to do with this library indeed. You can use PHP-Shapefile to read any shapefile in any CRS.
Converting them from one CRS to another is a task for a different library/piece of software.

In your case, conversion between projected coordinates (UTM) and Lat/Lon is a trivial one. Factory standard is actually PROJ library, but depending on your software stack, you can use PostGIS, SpatialLite, etc. Or even a custom written function, as it is just a mathematical process involved in a transformation between UTM and latlon coordinates.
