### ISSUE TITLE
Get DBF fields

### ISSUE THREAD

**Issue by fulf** [gasparesganga/php-shapefile#8]
Hello! Currently there is no way of finding out the DBF fields non-destructively (without getting a record).

Could you create a public method that returns the DBF fields all by itself? :)

It might be just a problem of returning the array_column($dbf_fields, 'name') I guess!

Thanks a lot. I really appreciate the work you're doing!

**Comment by gasparesganga** [comment]
Yep, that's a nice idea.
I've never needed that for my personal purposes, but it could be quite useful indeed.
I will work on it this very evening and possibly release a new version with this feature within tomorrow.

**Comment by fulf** [comment]
Thank you!

**Comment by gasparesganga** [comment]
Here you go, that was an easy one.
I've just released [v2.1.0](https://github.com/gasparesganga/php-shapefile/commit/856603fda39686f4c7d5d39fa55ff46a29cc6965) which includes a `getDBFFields()` method.

You can refer to the official [documentation](http://gasparesganga.com/labs/php-shapefile/#getdbffields) for the details, but it's really as straightforward as it gets:

``` php?start_inline=1
print_r( $ShapeFile->getDBFFields() );
```

Thank you for your feedback, I appreciate it.
